# Generated by Django 4.0.3 on 2023-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('ingredients', models.TextField()),
                ('cooking_methods', models.TextField()),
                ('recipe_url', models.FilePathField(blank=True, path='recipes/')),
            ],
        ),
    ]
