# Generated by Django 4.2.6 on 2023-11-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebcookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField(max_length=4)),
                ('height', models.IntegerField(max_length=5)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
