# Generated by Django 4.2.6 on 2023-11-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcookuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='webcookuser',
            name='height',
        ),
        migrations.RemoveField(
            model_name='webcookuser',
            name='weight',
        ),
    ]
