# Generated by Django 4.2.6 on 2023-11-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_webcookuser_age_remove_webcookuser_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcookuser',
            name='age',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcookuser',
            name='height',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcookuser',
            name='weight',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
