# Generated by Django 4.2.6 on 2023-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_webcookuser_age_webcookuser_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcookuser',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='webcookuser',
            name='height',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='webcookuser',
            name='weight',
            field=models.CharField(max_length=4),
        ),
    ]
