# Generated by Django 4.2.6 on 2023-11-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_webcookuser_age_alter_webcookuser_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcookuser',
            name='gender',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
