# Generated by Django 4.2.6 on 2023-11-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_webcookuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcookuser',
            name='gender',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
