# Generated by Django 4.2.6 on 2023-11-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_webcookuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcookuser',
            name='gender',
            field=models.CharField(null=True),
        ),
    ]
