# Generated by Django 4.2.6 on 2023-12-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_webcookuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcookuser',
            old_name='name',
            new_name='username',
        ),
    ]
