# Generated by Django 4.0.3 on 2023-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_url',
            field=models.FilePathField(blank=True, path='recipes/'),
        ),
    ]
