# Generated by Django 4.2.5 on 2023-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_recipe_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_url',
            field=models.FilePathField(blank=True, path='Recipes/'),
        ),
    ]
