# Generated by Django 4.2.5 on 2023-10-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_recipe_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
