# Generated by Django 4.2.5 on 2023-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_remove_recipe_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/'),
        ),
    ]
